#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

#define TAG "BounceBall"

/* generated by fbt from .png files in images folder */
#include <bounce_ball_icons.h>

/** ids for all scenes used by the app */
typedef enum {
    BBAppScene_MainMenu,
    BBAppScene_FirstPopup,
    BBAppScene_SecondPopup,
    BBAppScene_count
} BBAppScene;

/** ids for the 2 types of view used by the app */
typedef enum{
    BBAppView_Menu,
    BBAppView_Popup,
} BBAppView;

/** the app context struct */
typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} BBApp;

/** all custom events */
typedef enum{
    BBAppEvent_ShowPopupOne,
    BBAppEvent_ShowPopupTwo,
} BBAppEvent;

/* main menu scene */

/** indices for menu items */
typedef enum{
    BBAppMenuSelection_One,
    BBAppMenuSelection_Two,
} BBAppMenuSelection;

/** main menu callback - sends a custom event to the scene manager based on the menu selection */
void BBApp_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "BBApp_menu_callback_main_menu");
    BBApp* app = context;
    switch(index) {
    case BBAppMenuSelection_One:
        scene_manager_handle_custom_event(app->scene_manager, BBAppEvent_ShowPopupOne);
        break;
    case BBAppMenuSelection_Two:
        scene_manager_handle_custom_event(app->scene_manager, BBAppEvent_ShowPopupTwo);
        break;
    }
}

/** resets the menu, gives it content, callbacks and selection enums */
void BBApp_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_on_enter_main_menu");
    BBApp* app = context;
    menu_reset(app->menu);

    // NB. icons are specified as NULL below, because:
    // * icons are _always_ animated by the menu
    // * the icons provided (&I_one, &I_two) are generated by the build process
    // * these icons do not have a framerate (resulting in a division by zero)
    menu_add_item(
        app->menu,
        "First popup",
        NULL,
        BBAppMenuSelection_One,
        BBApp_menu_callback_main_menu,
        app);
    menu_add_item(
        app->menu,
        "Second popup",
        NULL,
        BBAppMenuSelection_Two,
        BBApp_menu_callback_main_menu,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, BBAppView_Menu);
}

/** main menu event handler - switches scene based on the event */
bool BBApp_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "BBApp_scene_on_event_main_menu");
    BBApp* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case BBAppEvent_ShowPopupOne:
            scene_manager_next_scene(app->scene_manager, BBAppScene_FirstPopup);
            consumed = true;
            break;
        case BBAppEvent_ShowPopupTwo:
            scene_manager_next_scene(app->scene_manager, BBAppScene_SecondPopup);
            consumed = true;
            break;
        }
        break;
    default: // eg. SceneManagerEventTypeBack, SceneManagerEventTypeTick
        consumed = false;
        break;
    }
    return consumed;
}

void BBApp_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_on_exit_main_menu");
    BBApp* app = context;
    menu_reset(app->menu);
}

/* popup 1 scene */

void BBApp_scene_on_enter_popup_one(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_on_enter_popup_one");
    BBApp* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup One", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, NULL);
    popup_set_text(app->popup, "One! One popup. Ah ah ah...", 32, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, BBAppView_Popup);
}

bool BBApp_scene_on_event_popup_one(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "BBApp_scene_on_event_popup_one");
    UNUSED(context);
    UNUSED(event);
    return false; // don't handle any events
}

void BBApp_scene_on_exit_popup_one(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_on_exit_popup_one");
    BBApp* app = context;
    popup_reset(app->popup);
}

/* popup 2 scene */

void BBApp_scene_on_enter_popup_two(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_on_enter_popup_two");
    BBApp* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup Two", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, NULL);
    popup_set_text(app->popup, "Two! Two popups. (press back)", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, BBAppView_Popup);
}

bool BBApp_scene_on_event_popup_two(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "BBApp_scene_on_event_popup_two");
    UNUSED(context);
    UNUSED(event);
    return false; // don't handle any events
}

void BBApp_scene_on_exit_popup_two(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_on_exit_popup_two");
    BBApp* app = context;
    popup_reset(app->popup);
}

/** collection of all scene on_enter handlers - in the same order as their enum */
void (*const BBApp_scene_on_enter_handlers[])(void*) = {
    BBApp_scene_on_enter_main_menu,
    BBApp_scene_on_enter_popup_one,
    BBApp_scene_on_enter_popup_two};

/** collection of all scene on event handlers - in the same order as their enum */
bool (*const BBApp_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    BBApp_scene_on_event_main_menu,
    BBApp_scene_on_event_popup_one,
    BBApp_scene_on_event_popup_two};

/** collection of all scene on exit handlers - in the same order as their enum */
void (*const BBApp_scene_on_exit_handlers[])(void*) = {
    BBApp_scene_on_exit_main_menu,
    BBApp_scene_on_exit_popup_one,
    BBApp_scene_on_exit_popup_two};

/** collection of all on_enter, on_event, on_exit handlers */
const SceneManagerHandlers BBApp_scene_event_handlers = {
    .on_enter_handlers = BBApp_scene_on_enter_handlers,
    .on_event_handlers = BBApp_scene_on_event_handlers,
    .on_exit_handlers = BBApp_scene_on_exit_handlers,
    .scene_num = BBAppScene_count};

/** custom event handler - passes the event to the scene manager */
bool BBApp_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "BBApp_scene_manager_custom_event_callback");
    furi_assert(context);
    BBApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

/** navigation event handler - passes the event to the scene manager */
bool BBApp_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "BBApp_scene_manager_navigation_event_callback");
    furi_assert(context);
    BBApp* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

/** initialise the scene manager with all handlers */
void BBApp_scene_manager_init(BBApp* app) {
    FURI_LOG_T(TAG, "BBApp_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&BBApp_scene_event_handlers, app);
}

/** initialise the views, and initialise the view dispatcher with all views */
void BBApp_view_dispatcher_init(BBApp* app) {
    FURI_LOG_T(TAG, "BBApp_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();

    // allocate each view
    FURI_LOG_D(TAG, "BBApp_view_dispatcher_init allocating views");
    app->menu = menu_alloc();
    app->popup = popup_alloc();

    // assign callback that pass events from views to the scene manager
    FURI_LOG_D(TAG, "BBApp_view_dispatcher_init setting callbacks");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, BBApp_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, BBApp_scene_manager_navigation_event_callback);

    // add views to the dispatcher, indexed by their enum value
    FURI_LOG_D(TAG, "BBApp_view_dispatcher_init adding view menu");
    view_dispatcher_add_view(app->view_dispatcher, BBAppView_Menu, menu_get_view(app->menu));

    FURI_LOG_D(TAG, "BBApp_view_dispatcher_init adding view popup");
    view_dispatcher_add_view(app->view_dispatcher, BBAppView_Popup, popup_get_view(app->popup));
}

/** initialise app data, scene manager, and view dispatcher */
BBApp* BBApp_init() {
    FURI_LOG_T(TAG, "BBApp_init");
    BBApp* app = malloc(sizeof(BBApp));
    BBApp_scene_manager_init(app);
    BBApp_view_dispatcher_init(app);
    return app;
}

/** free all app data, scene manager, and view dispatcher */
void BBApp_free(BBApp* app) {
    FURI_LOG_T(TAG, "BBApp_free");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, BBAppView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, BBAppView_Popup);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->menu);
    popup_free(app->popup);
    free(app);
}

/** go to trace log level in the dev environment */
void BBApp_set_log_level() {
#ifdef FURI_DEBUG
    furi_log_set_level(FuriLogLevelTrace);
#else
    furi_log_set_level(FuriLogLevelInfo);
#endif
}

/** entrypoint */
int32_t bounce_ball_app(void* p) {
    UNUSED(p);
    BBApp_set_log_level();

    // create the app context struct, scene manager, and view dispatcher
    FURI_LOG_I(TAG, "Bounce ball app starting...");
    BBApp* app = BBApp_init();

    // set the scene and launch the main loop
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, BBAppScene_MainMenu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "Bounce ball app finishing...");
    furi_record_close(RECORD_GUI);
    BBApp_free(app);
    return 0;
}
