#include <furi.h>
#include <furi_hal.h>

#include <gui/gui.h>
#include <gui/view.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_input.h>
#include <gui/modules/widget.h>
#include <gui/modules/variable_item_list.h>

#include <notification/notification.h>
#include <notification/notification_messages.h>

/* generated by fbt from .png files in images folder */
#include <bounce_ball_icons.h>

#define TAG "BounceBall"

// Change to BACKLIGHT_AUTO if backlight should be able to power off
#define BACKLIGHT_ON 1

// App menu has 3 items
typedef enum {
    BB_SubmenuIndexConfigure,
    BB_SubmenuIndexGame,
    BB_SubmenuIndexAbout,
} BB_SubmenuIndex;

int32_t bounce_ball_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm bounce_ball!");

    return 0;
}
